"""Replay the deterministic fuzz corpus against the hostile parsers.

The corpus under tests/fuzz/corpus/ is checked in and generated by
tests/fuzz/generate_corpus.py, so every input is a file that
reproduces forever, not a seed. A parser fed a hostile input must do
one of two honest things: handle it, or refuse it with a locatable
SystemExit. What it must never do is raise an uncaught internal
exception (a traceback out of yaml, xml, or re is a crash, not a
refusal), hang, or silently escape its safety envelope.

The parsers under test are the ones that meet untrusted bytes: config
YAML, DOCX XML, public-site HTML, and zip member names.
"""

from __future__ import annotations

from pathlib import Path

import pytest

CORPUS = Path(__file__).resolve().parent / "fuzz" / "corpus"


def _cases(kind: str, suffix: str):
    return sorted((CORPUS / kind).glob(f"*{suffix}"))


@pytest.mark.invariant("INV-config-locatable")
@pytest.mark.layer("property")
@pytest.mark.proof("negative")
@pytest.mark.parametrize("path", _cases("yaml", ".yaml"), ids=lambda p: p.name)
def test_config_yaml_never_crashes(path, tmp_path):
    """A hostile config file is either a mapping or a locatable refusal,
    never a raw parser traceback."""

    from press import booklib

    target = tmp_path / "metadata.yaml"
    target.write_bytes(path.read_bytes())
    try:
        result = booklib.load_config_mapping(target, required=True)
    except SystemExit:
        return  # a named refusal is the correct outcome
    assert isinstance(result, dict)


@pytest.mark.invariant("INV-format-witness")
@pytest.mark.layer("property")
@pytest.mark.proof("negative")
@pytest.mark.parametrize("path", _cases("docx", ".bin"), ids=lambda p: p.name)
def test_docx_extract_never_crashes(path):
    """DOCX text extraction over arbitrary bytes returns a string and
    does not raise an XML parser error."""

    from press import verify_formats

    result = verify_formats.docx_visible_text(path.read_bytes())
    assert isinstance(result, str)


@pytest.mark.invariant("INV-pages-refs")
@pytest.mark.layer("property")
@pytest.mark.proof("negative")
@pytest.mark.parametrize("path", _cases("html", ".html"), ids=lambda p: p.name)
def test_pages_scan_never_crashes(path):
    """The pages scanner over hostile HTML yields references and ids
    without raising."""

    from press import verify_pages

    scan = verify_pages.PageScan()
    scan.feed(path.read_text(encoding="utf-8", errors="replace"))
    assert isinstance(scan.refs, list)
    assert isinstance(scan.ids, set)


@pytest.mark.invariant("INV-archive-source-policy")
@pytest.mark.layer("property")
@pytest.mark.proof("negative")
@pytest.mark.parametrize("path", _cases("member", ".txt"), ids=lambda p: p.name)
def test_member_safety_never_escapes(path):
    """member_safe returns a bool for any name, and never admits a name
    that escapes its prefix (absolute, traversal, or embedded dotdot)."""

    from press import verify_archives

    name = path.read_text(encoding="utf-8")
    verdict = verify_archives.member_safe(name, "site")
    assert isinstance(verdict, bool)
    if name.startswith("/") or ".." in name.replace("\\", "/").split("/"):
        assert verdict is False


def test_corpus_is_present_and_nonempty():
    """The checked-in corpus must exist; an empty corpus would make the
    parametrized cases vacuously pass."""

    files = list(CORPUS.rglob("*"))
    assert sum(1 for f in files if f.is_file()) >= 30
