"""Channel checklists: press publish kdp|ingram.

The press cannot upload to retail channels (they have no APIs worth
trusting), so it does the next honest thing: emit a checklist of
exactly what the channel needs, with the items the press already
produced checked off and their paths attached, and the items only a
person can do left unchecked. The document is generated from config and
the dist directory, never written by hand.
"""

from __future__ import annotations

from pathlib import Path

from . import booklib, gen_coverwrap

CHANNELS = {
    "kdp": {
        "name": "Amazon KDP",
        "manual": [
            "KDP account with tax interview completed",
            "Category selections (2 allowed; note 10 keyword slots)",
            "Pricing per marketplace and royalty option (60% print)",
            "Order a physical proof before approving publication",
        ],
    },
    "ingram": {
        "name": "IngramSpark",
        "manual": [
            "IngramSpark account and title setup fee",
            "BISAC subject codes (3 allowed)",
            "Wholesale discount and returns policy decisions",
            "Order a physical proof before enabling distribution",
        ],
    },
}


def artifact(path: Path, label: str) -> str:
    mark = "x" if path.is_file() else " "
    note = str(path) if path.is_file() else f"{path} (missing; build it)"
    return f"- [{mark}] {label}: {note}"


def main(channel: str) -> int:
    if channel not in CHANNELS:
        raise SystemExit(f"unknown channel {channel!r}: {', '.join(CHANNELS)}")
    root = booklib.root()
    meta = booklib.metadata()
    if not meta.get("title") or not meta.get("author"):
        raise SystemExit("the checklist needs title and author in config/metadata.yaml")
    slug = booklib.slug()
    dist = root / "dist"
    trim = meta.get("trim") or {}
    trim_w, trim_h = float(trim.get("width", 6)), float(trim.get("height", 9))
    isbn = gen_coverwrap.isbn_for_print()
    spec = CHANNELS[channel]

    interior = dist / f"{slug}-interior.pdf"
    lines = [
        f"# {spec['name']} checklist: {meta['title']}",
        "",
        f"Generated by the press from config and dist/. Trim {trim_w:g} x "
        f"{trim_h:g} in, bleed {gen_coverwrap.BLEED_IN} in on the wrap.",
        "",
        "## Files the channel needs",
        "",
        artifact(interior, "Print interior PDF (mirrored margins, black ink)"),
        artifact(dist / f"{slug}-coverwrap.pdf", "Cover wrap PDF (trim + bleed, spine computed)"),
        artifact(dist / f"{slug}.epub", "EPUB (KDP eBook / Ingram ebook program)"),
        artifact(root / "assets" / "cover.jpg", "Marketing cover image (front board only)"),
        "",
        "## Identity the channel will ask for",
        "",
        f"- [{'x' if isbn else ' '}] Print ISBN: {isbn or '[ISBN pending] in config registrations block'}",
        f"- [x] Title: {meta['title']}",
        f"- [x] Subtitle: {meta.get('subtitle', '')}",
        f"- [x] Author: {', '.join(booklib.book().authors)}",
        f"- [x] Description: {meta.get('description', '').strip()}",
        f"- [x] Keywords: {', '.join(meta.get('keywords') or [])}",
        "",
        "## Only a person can do these",
        "",
        *[f"- [ ] {item}" for item in spec["manual"]],
        "",
    ]
    out = dist / f"publish-{channel}.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"checklist -> {out.relative_to(root)}")
    missing = [line for line in lines if "(missing; build it)" in line]
    for line in missing:
        print(f"  {line}")
    return 0
