#!/usr/bin/env bash
# Regenerate requirements-lock.txt: the press's runtime dependencies, pinned to
# exact versions and hashes, resolved from pyproject.toml in the pinned
# toolchain container so the versions and Python match the platform a release
# installs on. --generate-hashes records every distribution's hash (all
# platforms plus the sdist), so the one lock is portable. Run this after
# changing [project.dependencies] in pyproject.toml, then run the gauntlet to
# prove press still builds and runs against the locked set.
set -euo pipefail
cd "$(dirname "$0")/.."
REPO="$PWD"

command -v docker >/dev/null 2>&1 || { echo "lock-deps: docker is required"; exit 2; }

image=$(grep -oE 'ghcr.io/clintecker/press-toolchain:sha-[0-9a-f]+@sha256:[0-9a-f]{64}' \
          .github/workflows/build.yml | head -1)
test -n "$image" || { echo "lock-deps: build.yml pins no toolchain @sha256 digest"; exit 1; }

case "$(uname -m)" in
  arm64|aarch64) platform="linux/arm64" ;;
  *)             platform="linux/amd64" ;;
esac

docker run --rm --platform "$platform" -v "$REPO":/src "$image" bash -euo pipefail -c '
  python3 -m pip install --break-system-packages -q pip-tools
  cp /src/pyproject.toml /tmp/pyproject.toml
  pip-compile --quiet --generate-hashes --strip-extras \
    --output-file=/src/requirements-lock.txt /tmp/pyproject.toml
'

# Rewrite the autogenerated header so the committed lock documents its own,
# runnable regeneration command rather than a container-internal path.
python3 - "$REPO/requirements-lock.txt" <<'PY'
import re, sys
p = sys.argv[1]
text = open(p, encoding="utf-8").read()
text = re.sub(r"#    pip-compile .*\n", "#    scripts/lock-deps.sh\n", text, count=1)
open(p, "w", encoding="utf-8").write(text)
PY
echo "lock-deps: regenerated requirements-lock.txt"
